### ISSUE TITLE
building with chlorine 1.0.9 for emscripten target fails

### ISSUE THREAD

**Issue by selassje** [Lokathor/chlorine#5]
Example failure:
https://github.com/selassje/nes-rs/runs/4178576437?check_suite_focus=true

Char Signedness for wasm is different compared to 1.0.7

**Comment by Lokathor** [comment]
The 1.0.9 definition did change to match the simplified logic that `cty` uses.

Cargo shouldn't be pulling 1.0.9 and 1.0.7 into the same build and causing this conflict.

In 1.0.7 the type was signed, and `cty` and 1.0.9 use unsigned.

the page here seems to indicate that signed was correct in thr first place: https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md

So I'm still confused why cargo is mixing two semver compatible versions of cty, but either way I'll move back to the correct (signed) definition.

**Comment by selassje** [comment]
Mixing? I only see it pulling one version. The TOML has  "1.0.7" so it can  be everything up to "2.0.0". For some  reason cargo  started to pull in 1.0.9 instead.

**Comment by Lokathor** [comment]
ah, right, i was misunderstanding the error. it's not a conflict between two versions of chlorine, it's a conflict between chlorine and std.

As to why 1.0.9 was pulled in, that's because cargo always picks the latest semver compatible version.

**Comment by Lokathor** [comment]
Okay, I put out 1.0.10 which should have wasm32 and wasm64 as signed, so things should be good.

**Comment by selassje** [comment]
Thanks, it builds again with 1.0.10
